### ISSUE TITLE
How to use it on egg or koa?

### ISSUE THREAD

**Issue by i-apples** [express-rate-limit/express-rate-limit#183]
I'm from China. I'm using the modified egg.js based on koa here. I think this package is very useful to me. Please give me some advice on how to use it on egg or KOA. Thank you

**Comment by i-apples** [comment]
ps: I'm a rookie
egg.js url: https://eggjs.org/en/index.html

**Comment by nfriedly** [comment]
Hi @i-apples,

I don't know if this works with Koa or egg, I've never use either one. 

I'll try to test it sometime, but I'm not sure how soon it will be.

**Comment by i-apples** [comment]
thank you

>

**Comment by nfriedly** [comment]
Although this is still not a supported use case, I recently came across https://www.npmjs.com/package/koa-connect and wanted to mention it here.

That said, egg and koa support is not a feature we plan to add directly, so I'm going to close this for now.
