### ISSUE TITLE
rate limiter can be bypassed easily if behind a reverse proxy that includes port numbers in "X-Forwarded-For" header

### ISSUE THREAD

**Issue by ngosset** [express-rate-limit/express-rate-limit#234]
A problem arises because the format of the "X-Forwarded-For" header isn't really 100% standardized between every reverse proxy out there, and Express is taking the first untrusted value and setting it as request.ip.

While some reverse proxy pass a comma delimited list of IP address, I've found other proxies will do a comma delimited list of IP:**PORT**. (And it's the source port, which unfortunately can change with every request)

For example, for Azure's Application Gateway this is documented here:

[_"The format for x-forwarded-for header is a comma-separated list of IP:port."_](https://docs.microsoft.com/en-us/azure/application-gateway/how-application-gateway-works#:~:text=X%2Dforwarded%2Dport%20specifies%20the,is%20routed%20to%20the%20backend.)

Your project uses request.ip as your key when storing the timer for a user. Express (as [documented ](https://expressjs.com/en/guide/behind-proxies.html) ), will set request.ip to the first untrusted address from the X-Forwarded-For header. However if the port is in X-Forwarded-For, then Express ends up including the port in request.ip

Because of this, a user can simply close and re-open their browser to bypass the rate-limit timer as their source port of their HTTP Request will change, even if their IP is the same. This could also be automated in some kind of script for API abuse.

Proposed solution: when generating your key for the store I'd recommend checking if request.ip matches IP or IP:PORT, and stripping the port if it matches the IP:PORT format.

**Comment by ngosset** [comment]
Alternatively if you leave it as is, it may just be worth just putting a note or example of stripping the port in doc for the "keyGenerator" Configuration Option so that other folks don't have to figure this out the hard way.

**Comment by ngosset** [comment]
I may be able to open a bug with express tomorrow.

**Comment by OmarOmeiri** [comment]
Isn't this an easy fix:

```ts
  keyGenerator(request: Request, _response: Response): string {
    if (!request.ip) {
      console.error(
        'WARN | `express-rate-limit` | `request.ip` is undefined. You can avoid this by providing a custom `keyGenerator` function, but it may be indicative of a larger issue.',
      );
    }

    return request.ip.replace(/:[^.]*$/, '');
  },
```

Is there some (to me, unapparent) reason why not to do it?

**Comment by gamemaker1** [comment]
Yes, I think that is the workaround @nfriedly mentioned [here](https://github.com/nfriedly/express-rate-limit/issues/234#issuecomment-839189175).

@nfriedly should we put this alongside the Troubleshooting Proxy Issues section in the wiki?

**Comment by nfriedly** [comment]
Yeah, we should probably do that.

**Comment by gamemaker1** [comment]
> https://github.com/nfriedly/express-rate-limit/issues/234#issuecomment-839172103

@ngosset were you able to open this issue?

> Yeah, we should probably do that. 

I'll add it then.

**Comment by florianwalther-private** [comment]
Help me understand this. Is this something a client can do or does this depend on my server setup? For example, does this problem exist with Nginx?

**Comment by nfriedly** [comment]
@florianwalther-private as far as I can tell, this is something weird that only Microsoft Azure does. I've never heard of anyone else putting the port in the X-Forwarded-For header. 

With nginx, you would presumably have control over the configuration, so no issue there.

**Comment by nfriedly** [comment]
I decided not to include the fix by default since it adds extra overhead that is unnecessary in most cases. 

However, starting with version 6.8.0, express-rate-limit now detects if there is a port number in the `req.ip` (or anything besides a valid IPv4 or IPv6) and logs an [ERR_ERL_INVALID_IP_ADDRESS](https://github.com/express-rate-limit/express-rate-limit/wiki/Error-Codes#err_erl_invalid_ip_address) on the first request. 

The 6.9.0 release should have a link to the wiki in the error message, and the wiki has the suggested fix and a link to this issue for more context.

So, I'm going to go ahead and close this.

**Comment by laneme** [comment]
Many of my projects are behind cloudflare. Is it not a good idea to set `req.ip` to cloudflare provided `cf-connecting-ip`?

**Comment by nfriedly** [comment]
@laneme It looks like CloudFlare also sets the `X-Forwarded-For` header: https://developers.cloudflare.com/fundamentals/get-started/reference/http-request-headers/#x-forwarded-for - so, express's `app.set('trust proxy', 1)` should be sufficient to get `req.ip` to be automatically set correctly.

But, if that doesn't work for some reason, then you could either manually override `req.ip`, or use a custom `keyGenerator` that returned the `cf-connecting-ip` header value, e.g.

```js
app.use(rateLimit({
  keyGenerator: req => req.headers['cf-connecting-ip'] || req.ip,
  // ...
});
```

See https://github.com/express-rate-limit/express-rate-limit/wiki/Troubleshooting-Proxy-Issues for more info.

**Comment by laneme** [comment]
Thank you. `keyGenerator` is what I go for. 

Like I had to set `trust proxy` to `2` to get my ip address using the test method provided in the [wiki](https://github.com/express-rate-limit/express-rate-limit/wiki/Troubleshooting-Proxy-Issues) when using both nginx & cloudflare. And if I suddenly remove/change proxies, this number has to change. 

Where `keyGenerator` gives me more control, I can detect trusted environment flags on the fly.
