### ISSUE TITLE
Multiple rate limits on one api route not working.

### ISSUE THREAD

**Issue by CalebJamesStevens** [express-rate-limit/express-rate-limit#331]
### Description

We have an api endpoint that sends out an email and we want to limit it to 15 times in 15 minutes and 100 times per day.

```
const emailUserLimiter = rateLimit({
    windowMs: 60 * 15 * 1000,
    max: 15,
    standardHeaders: true,
    legacyHeaders: false,
    message: 'Too many requests in 15 minutes',
  });
  const emailUserOtherLimiter = rateLimit({
    windowMs: 60 * 1000 * 86400,
    max: 100,
    standardHeaders: true,
    legacyHeaders: false,
    message: 'Too many requests in a day',
  });
  server.post(
    '/api/users/email-user',
    emailUserOtherLimiter,
    emailUserLimiter,
  );
  ```
  
This works in localhost but outside of localhost i see multiple instances of the 15 minutes limiter each with it owns current count running and not a single response with the daily limiter. 

For example i will hit the api 10 times within a few seconds and this is the data show in the response headers.
```
ratelimit-limit: 15
ratelimit-remaining: 14
ratelimit-reset: 563

ratelimit-limit: 15
ratelimit-remaining: 14
ratelimit-reset: 563

ratelimit-limit: 15
ratelimit-remaining: 13
ratelimit-reset: 562

ratelimit-limit: 15
ratelimit-remaining: 12
ratelimit-reset: 562

ratelimit-limit: 15
ratelimit-remaining: 14
ratelimit-reset: 562

ratelimit-limit: 15
ratelimit-remaining: 14
ratelimit-reset: 561

ratelimit-limit: 15
ratelimit-remaining: 13
ratelimit-reset: 561

ratelimit-limit: 15
ratelimit-remaining: 13
ratelimit-reset: 561

ratelimit-limit: 15
ratelimit-remaining: 11
ratelimit-reset: 543

ratelimit-limit: 15
ratelimit-remaining: 14
ratelimit-reset: 537

```

And it continues like this. All using the same timer but the rate limit keeps being reset. 

  

### Library version

^6.3.0

### Node version

v14.17.5

### Module system

ESM

**Comment by nfriedly** [comment]
Does your production environment run multiple servers, and/or multiple node.js processes (e.g. with the cluster module?) The default memory store has a separate hit counter for each process, so that would explain the behavior you're seeing. Any of the external stores would be synchronized across all servers/processes, but you would need to ensure that the two instances use different keys.

Also, you probably don't want both limiters setting headers, as the second one will overwrite the headers set by the first one.

**Comment by jsfelix** [comment]
I am using redis to store, but multiple windows aren't working.

I set some routes to 1s windows, and other ones to 30s, but all routes are set to 30s.

**Comment by gamemaker1** [comment]
Hi @jsfelix,

This seems to be a different problem than the one faced by the original poster of this issue. Could you please open a new issue, where we could help you solve your problem?

Thanks!

**Comment by jsfelix** [comment]
sure!

Maybe the problem is with multiple window sizes. I will open the issue

**Comment by sidonaldson** [comment]
> Here is the implementation:
> 
> ```ts
> import rateLimit from 'express-rate-limit';
> import RedisStore from 'rate-limit-redis';
> import { createClient } from 'redis';
> 
> const client = createClient();
> 
> client.connect();
> 
> export const apiLimiter = rateLimit({
>   windowMs: 30 * 1000, // 30 seconds
>   max: 100,
>   standardHeaders: true,
>   legacyHeaders: false,
>   store: new RedisStore({
>     sendCommand: (...args: string[]) => client.sendCommand(args),
>   }),
> });
> 
> export const paymentLimiter = rateLimit({
>   windowMs: 1000, // 1 second
>   max: 1,
>   standardHeaders: true,
>   legacyHeaders: false,
>   store: new RedisStore({
>     sendCommand: (...args: string[]) => client.sendCommand(args),
>   }),
> });
> ```

Just in case you still need a solution - RedisStore takes a prefix property. I use one Redis for two envs so pass the env as a prefix, the name of the limiter instance and append a string as well to make sure there's no crossover

```JavaScript
const rateLimitFactory = ({ redis, prefix, name, windowMs, limit, message }) =>
  rateLimit({
    windowMs, // how many ms
    limit, // Limit each IP to N requests per `window`
    standardHeaders: true, // Return rate limit info in the `RateLimit-*` headers
    legacyHeaders: false, // Disable the `X-RateLimit-*` headers
    validate: true, // check for config issues
    message: message ?? "Too many requests, please try again later.", // message to send
    skip: (req, _res) => allowlist.includes(req.ip), // skip callback
    store: new RedisStore({
      sendCommand: (...args) => redis.call(...args),
      prefix: prefix + name + "_rateLimit",
    }),
  });
```

**Comment by Android-44-kitkat783** [comment]
> Does your production environment run multiple servers, and/or multiple node.js processes (e.g. with the [cluster](https://www.fullstory.com/careers/) module)?
> 
> The default memory store has a separate hit counter for each process, so that would explain the behavior you're seeing. Any of the external stores would be synchronized across all servers/processes, but you would need to ensure that the two instances use different keys, otherwise requests will be double-counted.
> 
> Also, you probably don't want both limiters setting headers, as the second one will overwrite the headers set by the first one.





https://blueputative80.github.io/W1mTOwdAI_HUDQQ/
