### ISSUE TITLE
Not working with Express router

### ISSUE THREAD

**Issue by manimalsmith23** [express-rate-limit/express-rate-limit#339]
### Description

Basically I want to rate limit by user id. I don't have access to the user id before my authentication middleware is run. I thought I could simply, call the auth middleware, then call the rate limiter, but it's not working. This is how the setup looks. Any help would be appreciated. Thank you.   
// The creation of the rate limit (assume I have access to the user id here)

```
export function bearer(
  request: Request,
  response: Response,
  next: NextFunction,
): RateLimitRequestHandler | void {
    return rateLimit({
      windowMs: 15 * 60 * 1000, // 15 minutes
      max: 500,
      keyGenerator: () => userId,
      standardHeaders: true, // Return rate limit info in the `RateLimit-*` headers
      legacyHeaders: false, // Disable the `X-RateLimit-*` headers
      store: new RedisStore({
        sendCommand: (...args: string[]) => client.sendCommand(args),
      }),
    });

this.app.use("/api/v1/", WorkoutsRouter);
```

// Then inside WorkoutsRouter

```
import * as RateLimiter from "./middleware/rate_limiter";
const router: Router = Router();

router.get("/workouts", Authenticate.bearer, RateLimiter.bearer,
  (request: Request, response: Response, next: NextFunction) => {
   // some logic
    BaseRouter.promiseHandler(promise, request, response, next);
  });
```

I hit the GET /workouts routes, run the authentication code, then it runs the RateLimiter function and server pauses forever as if next() is never called. I don't understand what is going on. Surely I can apply this to an individual route without using app.use()?

**Comment by gamemaker1** [comment]
Hi @manimalsmith23,

You are right, `next()` isn't being called here, so it will pause forever 😅. Also, it looks like you are creating a new rate limiter for each route, which may not be your intention.

If I may suggest an alternative method:

```js
// server.js
// Creates and runs the server on the port specified in the configuration.

import createServer from 'express'

import { auth } from './services/auth.js'

// Create a server.
const app = createServer()

// Run middleware that authenticates the user.
app.use((request, response, next) => {
	// Authenticate the user.
	const user = auth.signin(request.headers.authorization)

	// Store the user on the request object, so we can use it later on.
	request.user = user
	next()
})

// Then, add the rate limiting middleware.
app.use(
	rateLimit({
		// A maximum of 500 requests can be made in a window of 1 hour.
		windowMs: 60 * 60 * 1000,
		max: 500,
		// Use the shiny new `RateLimit-*` headers.
		standardHeaders: true,
		legacyHeaders: false,
		// Use either the user ID (if the user is authenticated), or their IP address.
		keyGenerator(request: Request): string {
			const userIdentifier = request.user?.id
			const requestIdentifier =
				(request.headers['x-forwarded-for'] as string)?.split(',')[0] ??
				request.headers['fastly-client-ip'] ??
				request.ip ??
				request.ips[0] ??
				request.connection.remoteAddress ??
				request.socket.remoteAddress

			return userIdentifier ?? requestIdentifier
		},
	})
)
```

However, in this approach, you will need to add an `if...else` check on `request.url` in the authentication middleware if you want to skip authentication for certain routes.

**Comment by nfriedly** [comment]
Be careful about those headers - if they're not being set by something in your stack, then that leaves you open for abuse by an end-user setting it to a random value.

Also, if you use the `app.set('trust proxy', 1)` setting, then `req.ip` will be prefilled with the `x-forwarded-for` header value from your proxy, so you don't need to check both of those - see http://expressjs.com/en/guide/behind-proxies.html

**Comment by manimalsmith23** [comment]
Thanks @gamemaker1. What exactly do you mean by this: "creating a new rate limiter for each route"?

**Comment by gamemaker1** [comment]
Actually I think I was wrong.

```js
import * as RateLimiter from "./middleware/rate_limiter";
const router: Router = Router();

router.get("/workouts", Authenticate.bearer, RateLimiter.bearer,
  (request: Request, response: Response, next: NextFunction) => {
   // some logic
    BaseRouter.promiseHandler(promise, request, response, next);
  });
```

Here, we are passing `RateLimiter.bearer` as a middleware function to express. Express will call that function and then proceed to the next middleware/handler you have passed to it; it does not care about what the middleware returns. Hence, the rate limiter you return in the `RateLimiter.bearer` function is ignored by express.

To make sure the rate limiter works, you should replace the `RateLimiter.bearer` with `RateLimiter.bearer()` so that the returned rate limiting function is the function express gets as middleware. Also, you might want to store the limiter in a variable in the file where you define the `RateLimiter.bearer` function and return that in the function so that you don't create a new rate limiter for every time the middleware is applied.
