### ISSUE TITLE
keyGenerator is not working for api key

### ISSUE THREAD

**Issue by yazanmimi2000** [express-rate-limit/express-rate-limit#345]
### Description

Hey! I am trying to use keyGenerator to rate limit based on api-key passed in the headers of the request however from testing it seems like it still does rate limiting per ip address? I tested from two different ip addresses sending a request where both use the same key "xxx" (with rate limit 2 as in supabase for that key) and each of them gets a rate limit of 2 when it should be the total for both of them to have rate limit of 2. please help

```js
app.enable('trust proxy');

app.use((req, res, next) => {
  // Get the API key from the request headers
  const apiKey = req.headers['x-api-key'];
  // Use supabaseClient to query the api_keys table
  supabaseClient.from('api_keys')
    .select('rate_limit,total_num_calls')
    .eq('api_key', apiKey)
    .then(response => {
      // Retrieve the rate limit from the response
      req.apiKey = apiKey;
      req.rateLimit = response.data[0].rate_limit;
      req.totalNumCalls = response.data[0].total_num_calls;
      console.log(response.data[0]);
      next();
    })
    .catch(error => {
      console.log(error);
      res.status(401).send({ error: 'Invalid API key' });
    });
});

// apply rate limit for the endpoints
const inputRateLimiter = rateLimit({
  windowMs: 60 * 60 * 1000,
  max: (req) => req.rateLimit,
  message: "Too many requests, please try again later or contact us to inquire about your plan.",
  keyGenerator: function(req, res) {
    return String(req.headers['x-api-key']);
  },
});

app.use(inputRateLimiter);
```

### Library version

6.7.0

### Node version

v12.18.2

### Module system

CommonJS

**Comment by yazanmimi2000** [comment]
@nfriedly @gamemaker1 any help is appreciated!

**Comment by gamemaker1** [comment]
Hi @yazanmimi2000,

I did not understand the problem you are facing -

> two different ip addresses sending a request where both use the same key "xxx" and each of them gets a rate limit of 2

This is the intended behaviour - if you use the same API key and make a request from IP A, it will increase the count by 1; if you make another request from IP B with the same API key, it will increase the count to 2; and if you make a third request it will not allow it to proceed as it has reached the rate limit for that API key.

> be the total for both of them to have rate limit of 2

The total hit count for that singular API key in the example above is indeed 2; the count is maintained against the key provided by the `keyGenerator` function.

**Comment by nfriedly** [comment]
Is there any chance that you're running either multiple processes (with the `cluster `module) or multiple server instances, and you're two different attempts were ending up hitting different instances?
