### ISSUE TITLE
Skip function doesn't stop redis command from being sent

### ISSUE THREAD

**Issue by manimalsmith23** [express-rate-limit/express-rate-limit#347]
### Description

If caching is disabled or I am in a test environment, I want to skip rate limiting. My rateLimit looks like this:

```
export const basic = rateLimit({
  skip: () => !Config.caching.enabled || process.env.NODE_ENV?.includes("test"),
  windowMs: 5 * 60 * 1000, // 5 minutes, time period over which the number of allowed requests is calculated.
  max: 10, // The maximum number of allowed requests that can be made within the specified time period in windowMs.
  keyGenerator: () => cls.getNamespace("request").get("requestIpAddress"), // The value used to generate a unique key to track the number of requests made.
  standardHeaders: true, // Return rate limit info in the `RateLimit-*` headers.
  legacyHeaders: false, // Disable the `X-RateLimit-*` headers.
  store: new RedisStore({
    // @ts-expect-error - Known issue: the `call` function is not present in @types/ioredis
    sendCommand: (...args: string[]):Promise<void> => redis.call(...args),
  }),
});
```
Then inside a router, the code looks something like: 

```
import * as RateLimiter from "./middleware/rate_limiter";
const router: Router = Router();

router.get("/photos", Authenticate.bearer, RateLimiter.basic,
  (request: Request, response: Response, next: NextFunction) => {
   // some logic
    BaseRouter.promiseHandler(promise, request, response, next);
  });
```
When caching is enabled and I'm not in a test env everything works as expected. But when I disable my cache, I expected the skip function to stop the attempt at creating a new Redis store and sending a command. It doesn't though. When I start the node app, I get `UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'call' of null UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'call' of null
    at RedisStore.sendCommand`

How can I go about fixing this? 

### Library version

6.7.0

### Node version

14

### Typescript version (if you are using it)

4.7.2

### Module system

ESM

**Comment by nfriedly** [comment]
I think that creating the instance of RedisStore triggers an initial request - https://github.com/wyattjoh/rate-limit-redis/blob/dcb5941c45325a8037bbb257882f745d9ee74b89/src/lib.ts#L45-L77

I don't think there's a way to selectively disable that, so you might just want to disable the entire rate limiter in that case:

```js
let limiter = null;
export const basic = (req, res, next) => {
  if (!Config.caching.enabled || process.env.NODE_ENV?.includes("test")) {
    return next();
  } 

  if (!limiter) {
    limiter = rateLimit({
      // skip: () => !Config.caching.enabled || process.env.NODE_ENV?.includes("test"),
      windowMs: 5 * 60 * 1000, // 5 minutes, time period over which the number of allowed requests is calculated.
      max: 10, // The maximum number of allowed requests that can be made within the specified time period in windowMs.
      keyGenerator: () => cls.getNamespace("request").get("requestIpAddress"), // The value used to generate a unique key to track the number of requests made.
      standardHeaders: true, // Return rate limit info in the `RateLimit-*` headers.
      legacyHeaders: false, // Disable the `X-RateLimit-*` headers.
      store: new RedisStore({
        // @ts-expect-error - Known issue: the `call` function is not present in @types/ioredis
        sendCommand: (...args: string[]):Promise<void> => redis.call(...args),
      }),
    });
  }

  return limiter(req,res,next);
}
```

I didn't test that, but hopefully it gives you the right idea.  It's basically a custom middleware that lazily creates the rate limiter (and the redis store) the first time it's needed.

It was written to handle `Config.caching.enabled` potentially changing at runtime - you could make it a little bit simpler if you know that the process will be restarted any time `Config.caching.enabled` changes, but this should work either way.

**Comment by manimalsmith23** [comment]
Thank you @nfriedly that is exactly what I was looking for and everything works perfectly now. Closing the issue.
