### ISSUE TITLE
rateLimit not being update

### ISSUE THREAD

**Issue by dfloresgonz** [express-rate-limit/express-rate-limit#353]
### Description

the rateLimit always stays the same, the current and remaining do not update, those values stay the same no matter how many request I do

```
 {
  limit: 10,
  current: 1,
  remaining: 9,
  resetTime: 2023-05-30T20:43:35.015Z
}
```

```js
const buscarEscuelaLimiter = rateLimit({
    //store: new MemcachedStore({ expiration: expiration, client: mc, prefix: 'remoteip2:' }),
    windowMs: 15 * 60 * 1000, // 15 minutes
    max: 10, // Limit each IP to 100 requests per `window` (here, per 15 minutes)
    //message: 'No se puede mostrar más información',
    standardHeaders: true, // Return rate limit info in the `RateLimit-*` headers
    legacyHeaders: false, // Disable the `X-RateLimit-*` headers
})
```

### Library version

6.7.0

### Node version

v14.16.0

### Module system

ESM

**Comment by dfloresgonz** [comment]
funny thing is that it is 13:43pm here and it shows 2023-05-30T20:43:35.015Z that's 5 hours ahead, idk if that causes the problem.

I'm working locally not deployed to a cloud yet.

**Comment by dfloresgonz** [comment]
after putting some logs in the index.cjs I found out the "this.hits" object does not accumulate the values push to it after every request, it always resets thus not incrementing the value and not getting to the limit, idk what causes this

**Comment by gamemaker1** [comment]
The headers look fine to me.

What is the `req.ip` that the server gets tho?

**Comment by dfloresgonz** [comment]
req.id is 127.0.0.1 because I'm in localhost

**Comment by gamemaker1** [comment]
Ohkay

**Comment by dfloresgonz** [comment]
I've noticed the init() gets called in each request that's why this this.hits object is resetting and never incrementing.

![image](https://github.com/express-rate-limit/express-rate-limit/assets/17581509/0a6c2f62-8526-4b33-b27f-8abdead96938)

**Comment by gamemaker1** [comment]
If `init` gets called every request that means the rate limiter is getting re-defined every API call - could you please share the part of your code where you register the rate limiter with the router/express app?

**Comment by dfloresgonz** [comment]
this is my router

```
'use strict'

var express         = require('express');
var UtilsController = require('../controllers/c_utils');
var api             = express.Router();
const rateLimit     = require('express-rate-limit')

const buscarEscuelaLimiter = rateLimit({
    windowMs: 15 * 60 * 1000,
    max: 10,
    message: 'limit reached, try later',
    standardHeaders: true,
    legacyHeaders: false,
})

api.get('/buscarEscuela', buscarEscuelaLimiter, global.ensureAuth, UtilsController.buscarEscuela)
module.exports = api;
```

index.js

```
'use strict'

const serverless = require('serverless-http');

var express = require('express'),
    app = express(),
    cors = require('cors');

app.use(cors({ 'origin': '*' }))
    .use(express.urlencoded({ limit: '5mb', extended: true }))
    .use(express.json({ limit: '5mb' }))

var r_utils = require('./routes/r_utils');

app.use('/base2/api/general', r_utils)
```

**Comment by gamemaker1** [comment]
I don't see anything wrong with the way the limiter is added to the express app.

Could you please try two things -

1. I made a small reproduction app [here](https://github.com/gamemaker1/test/tree/rate-limit-repro), could you try modifying it until you hit the same issue?
2. Could you add a print statement where `init` is [supposed to be called](https://github.com/express-rate-limit/express-rate-limit/blob/1c52737cee9ee123b0893332856044138f64e681/source/lib.ts#L236) and see if it is called?

**Comment by nfriedly** [comment]
> I'm using serverless offline, would that be the problem?

I think that, combined with using the default MemoryStore, is the source of the problem. The serverless bit is likely starting a new process for each request, and that starts with a blank MemoryStore.

You can switch to one of the alternate stores that keeps the data outside of the process.

**Comment by dfloresgonz** [comment]
> You can switch to one of the alternate stores that keeps the data outside of the process.

I've tried memcached

![image](https://github.com/express-rate-limit/express-rate-limit/assets/17581509/46f8ec82-8abc-416e-b1af-c74bba22ac06)

I see the counter increasing but the request passes through 

![image](https://github.com/express-rate-limit/express-rate-limit/assets/17581509/9b843056-2212-412e-b5ef-a308d77e1dfc)

**Comment by gamemaker1** [comment]
Also, what is the value of `req.rateLimit`?

**Comment by dfloresgonz** [comment]
> Also, what is the value of `req.rateLimit`?

{ limit: 10, current: true, remaining: 9, resetTime: undefined }

**Comment by gamemaker1** [comment]
The value of `current` shouldn't be true, it should be a number.

What version of memcached are you using?

**Comment by dfloresgonz** [comment]
> Is it because the values of expiration and windowMs are different? Or does `expiration` have a different meaning for the memcached store?

I've tried putting the same values, but still the same

![image](https://github.com/express-rate-limit/express-rate-limit/assets/17581509/9664c28f-0d93-42a8-a083-59185f3b493f)

**Comment by dfloresgonz** [comment]
memcached version 1.4.17

**Comment by gamemaker1** [comment]
Oh no I meant the memcached store, sorry!

**Comment by gamemaker1** [comment]
It seems the memcached store returns the value returned by the memcached client itself, which can be [either a boolean or an integer](https://github.com/linyows/rate-limit-memcached/blob/a787145d12d8a1931d7353aff166bc5960cf7733/src/memcached-store.ts#L23) -

https://github.com/linyows/rate-limit-memcached/blob/a787145d12d8a1931d7353aff166bc5960cf7733/src/memcached-store.ts#L35

It still does the same in the latest version too (1.0.0).

Since it returns `true`, and `true > 10` returns `false`, the limiting mechanism is [never triggered](https://github.com/express-rate-limit/express-rate-limit/blob/1c52737cee9ee123b0893332856044138f64e681/source/lib.ts#L347).

**Comment by dfloresgonz** [comment]
but when I get the value from mecached using prefix+key 'remoteip2:127.0.0.1'

I get a number

**Comment by gamemaker1** [comment]
I couldn't even find the `increment` function that the store is calling - it's called `incr` in [the docs](https://github.com/3rd-Eden/memcached#public-methods) as well as the [typings package](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f785493e3ea014612513f5d0674909e7279ccb38/types/memcached/index.d.ts#L95).

**Comment by gamemaker1** [comment]
> but when I retrieve the value from memcached using prefix+key 'remoteip2:127.0.0.1'
> I get a number

Could you please try calling both the `increment` and `incr` functions, and see what they return?

**Comment by dfloresgonz** [comment]
how can I call those functions?

**Comment by gamemaker1** [comment]
Can you try `store.client.incr()`?

**Comment by dfloresgonz** [comment]
where do I do that? sorry cannot locate the store object

**Comment by gamemaker1** [comment]
Store the store object as a variable and then pass it to the rate limiter, like so -

```ts
const memStore = new MemcachedStore(...)

const limiter = rateLimit({ store: memStore, ... })

memStore.incr(...)
```

**Comment by dfloresgonz** [comment]
I got true as result of the incr function

![image](https://github.com/express-rate-limit/express-rate-limit/assets/17581509/26bab27c-29e2-498e-b322-0aaaaf023122)

**Comment by dfloresgonz** [comment]
I was using memjs library but I should user memcached lib right? 
the thing is that I cannot pass the credentials to my memcache server

**Comment by gamemaker1** [comment]
> I got true as result of the incr function

Oof that's a problem :/

The memcached store's `store.increment` function returns `true` instead of returning the total number of hits, which results in the rate limit never being triggered -

> https://github.com/express-rate-limit/express-rate-limit/issues/353#issuecomment-1570333821

Could you open an issue on the rate-limit-memcached repo about this?

A temporary fix could be to edit the rate-limit-memcached code file and return the total hits manually in the `store.increment` function.

**Comment by gamemaker1** [comment]
Hi @dfloresgonz,

Were you able to make the store work using the workaround I mentioned above?

> A temporary fix could be to edit the rate-limit-memcached code file and return the total hits manually in the store.increment function.

Regards

**Comment by nfriedly** [comment]
BTW, I looked into this just now, and the reason it was returning true is that rate-limit-memcached [expects the second argument passed to the callback to be the value of the key or false](https://github.com/express-rate-limit/rate-limit-memcached/blob/2c04518b4ef9df486cd6b527bbad32c84d8c3583/src/memcached-store.ts#L23) to indicate the key didn't exist, but memjs's increment function [passes a success boolean as the second argument and the value as the third argument](https://github.com/memcachier/memjs/blob/f10b26006e1a40394dc192f9edd628c0ec43189a/lib/memjs/memjs.js#L417).

https://github.com/express-rate-limit/express-rate-limit/pull/379 will detect and warn about this kind of mismatch in  the future.
