### ISSUE TITLE
ratelimit-remaining not decreasign few times

### ISSUE THREAD

**Issue by Rajdev2011** [express-rate-limit/express-rate-limit#354]
### Description

Hi 

Iam using express-rate-limit in node js as backend api and front end react js.

Iam trying to use rate-limit for otp and my unique id is mobile number 

when i check headers ratelimit-remaining is not decreasing quickly it is decreasing some times twice hit or trice hit.

```
const merchantOtpLimiter = rateLimit({
        windowMs: 15 * 60 * 1000, // 15 minutes window
        max: 4, // limit each IP to 5 requests per windowMs
        message: {
            "success": false,
            "message": "You have reached the maximum number of attempts. Please try after 15 minutes",
        },
        statusCode: 200,
        standardHeaders: true, // Return rate limit info in the `RateLimit-*` headers
        legacyHeaders: false, // Disable the `X-RateLimit-*` headers
        delayMs: 0,
        keyGenerator: function (req) {

            if (req.body.mobile) {
                return String("merchantOtpLimiter" + req.body.mobile);
            }
            else if (req.body.customer_mobile) {
                return String("merchantOtpLimiter" + req.body.customer_mobile);
            }
}
})
```

### Library version

express-rate-limit

### Node version

16

### Module system

ESM

**Comment by gamemaker1** [comment]
Hi @Rajdev2011,

Could you please share the headers and the timestamps of the requests when this problem occurs?

Thanks

**Comment by Rajdev2011** [comment]
Hi Gamemaker thanks for the reply.

Please check below request and response headers it behave weird rate limit count 3 and then 2 and then 3 ...... 


POST /api/merchant/checkMerchantOTP HTTP/2
Host: aasaanapi.aasaancheckout.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Authorization: Bearer null
Content-Type: application/json
Content-Length: 36
Origin: https://aasaanmerchant.aasaancheckout.com
Connection: keep-alive
Referer: https://aasaanmerchant.aasaancheckout.com/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
TE: trailers


HTTP/2 200 OK
date: Sat, 10 Jun 2023 14:36:50 GMT
content-type: application/json; charset=utf-8
content-length: 85
x-powered-by: Express
access-control-allow-origin: https://aasaanmerchant.aasaancheckout.com
vary: Origin
access-control-allow-credentials: true
access-control-expose-headers: Access-Control-Allow-Origin
x-frame-options: DENY
ratelimit-limit: 4
ratelimit-remaining: 3
ratelimit-reset: 894
etag: W/"55-0AGZZoNQmHjnZm+9v14hT58th1M"
X-Firefox-Spdy: h2




-------------------

POST /api/merchant/checkMerchantOTP HTTP/2
Host: aasaanapi.aasaancheckout.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Authorization: Bearer null
Content-Type: application/json
Content-Length: 36
Origin: https://aasaanmerchant.aasaancheckout.com
Connection: keep-alive
Referer: https://aasaanmerchant.aasaancheckout.com/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
TE: trailers


HTTP/2 200 OK
date: Sat, 10 Jun 2023 14:37:14 GMT
content-type: application/json; charset=utf-8
content-length: 85
x-powered-by: Express
access-control-allow-origin: https://aasaanmerchant.aasaancheckout.com
vary: Origin
access-control-allow-credentials: true
access-control-expose-headers: Access-Control-Allow-Origin
x-frame-options: DENY
ratelimit-limit: 4
ratelimit-remaining: 2
ratelimit-reset: 869
etag: W/"55-0AGZZoNQmHjnZm+9v14hT58th1M"
X-Firefox-Spdy: h2


-------------------------------------------------------------------

POST /api/merchant/checkMerchantOTP HTTP/2
Host: aasaanapi.aasaancheckout.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Authorization: Bearer null
Content-Type: application/json
Content-Length: 36
Origin: https://aasaanmerchant.aasaancheckout.com
Connection: keep-alive
Referer: https://aasaanmerchant.aasaancheckout.com/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
TE: trailers

HTTP/2 200 OK
date: Sat, 10 Jun 2023 14:37:37 GMT
content-type: application/json; charset=utf-8
content-length: 85
x-powered-by: Express
access-control-allow-origin: https://aasaanmerchant.aasaancheckout.com
vary: Origin
access-control-allow-credentials: true
access-control-expose-headers: Access-Control-Allow-Origin
x-frame-options: DENY
ratelimit-limit: 4
ratelimit-remaining: 3
ratelimit-reset: 846
etag: W/"55-0AGZZoNQmHjnZm+9v14hT58th1M"
X-Firefox-Spdy: h2


----------------------------

POST /api/merchant/checkMerchantOTP HTTP/2
Host: aasaanapi.aasaancheckout.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Authorization: Bearer null
Content-Type: application/json
Content-Length: 36
Origin: https://aasaanmerchant.aasaancheckout.com
Connection: keep-alive
Referer: https://aasaanmerchant.aasaancheckout.com/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
TE: trailers

HTTP/2 200 OK
date: Sat, 10 Jun 2023 14:37:58 GMT
content-type: application/json; charset=utf-8
content-length: 85
x-powered-by: Express
access-control-allow-origin: https://aasaanmerchant.aasaancheckout.com
vary: Origin
access-control-allow-credentials: true
access-control-expose-headers: Access-Control-Allow-Origin
x-frame-options: DENY
ratelimit-limit: 4
ratelimit-remaining: 1
ratelimit-reset: 825
etag: W/"55-0AGZZoNQmHjnZm+9v14hT58th1M"
X-Firefox-Spdy: h2

-----------------------------------

POST /api/merchant/checkMerchantOTP HTTP/2
Host: aasaanapi.aasaancheckout.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Authorization: Bearer null
Content-Type: application/json
Content-Length: 36
Origin: https://aasaanmerchant.aasaancheckout.com
Connection: keep-alive
Referer: https://aasaanmerchant.aasaancheckout.com/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
TE: trailers


HTTP/2 200 OK
date: Sat, 10 Jun 2023 14:38:23 GMT
content-type: application/json; charset=utf-8
content-length: 85
x-powered-by: Express
access-control-allow-origin: https://aasaanmerchant.aasaancheckout.com
vary: Origin
access-control-allow-credentials: true
access-control-expose-headers: Access-Control-Allow-Origin
x-frame-options: DENY
ratelimit-limit: 4
ratelimit-remaining: 2
ratelimit-reset: 800
etag: W/"55-0AGZZoNQmHjnZm+9v14hT58th1M"
X-Firefox-Spdy: h2

-----------------------------------------------------------------

POST /api/merchant/checkMerchantOTP HTTP/2
Host: aasaanapi.aasaancheckout.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Authorization: Bearer null
Content-Type: application/json
Content-Length: 36
Origin: https://aasaanmerchant.aasaancheckout.com
Connection: keep-alive
Referer: https://aasaanmerchant.aasaancheckout.com/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
TE: trailers


HTTP/2 200 OK
date: Sat, 10 Jun 2023 14:38:46 GMT
content-type: application/json; charset=utf-8
content-length: 85
x-powered-by: Express
access-control-allow-origin: https://aasaanmerchant.aasaancheckout.com
vary: Origin
access-control-allow-credentials: true
access-control-expose-headers: Access-Control-Allow-Origin
x-frame-options: DENY
ratelimit-limit: 4
ratelimit-remaining: 0
ratelimit-reset: 777
etag: W/"55-0AGZZoNQmHjnZm+9v14hT58th1M"
X-Firefox-Spdy: h2


----------------------------------------------

POST /api/merchant/checkMerchantOTP HTTP/2
Host: aasaanapi.aasaancheckout.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Authorization: Bearer null
Content-Type: application/json
Content-Length: 36
Origin: https://aasaanmerchant.aasaancheckout.com
Connection: keep-alive
Referer: https://aasaanmerchant.aasaancheckout.com/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
TE: trailers


HTTP/2 200 OK
date: Sat, 10 Jun 2023 14:39:14 GMT
content-type: application/json; charset=utf-8
content-length: 85
x-powered-by: Express
access-control-allow-origin: https://aasaanmerchant.aasaancheckout.com
vary: Origin
access-control-allow-credentials: true
access-control-expose-headers: Access-Control-Allow-Origin
x-frame-options: DENY
ratelimit-limit: 4
ratelimit-remaining: 1
ratelimit-reset: 749
etag: W/"55-0AGZZoNQmHjnZm+9v14hT58th1M"
X-Firefox-Spdy: h2

**Comment by Rajdev2011** [comment]
POST /api/merchant/checkMerchantOTP HTTP/2
Host: aasaanapi.aasaancheckout.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Authorization: Bearer null
Content-Type: application/json
Content-Length: 36
Origin: https://aasaanmerchant.aasaancheckout.com
Connection: keep-alive
Referer: https://aasaanmerchant.aasaancheckout.com/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
TE: trailers


HTTP/2 200 OK
date: Sat, 10 Jun 2023 14:36:50 GMT
content-type: application/json; charset=utf-8
content-length: 85
x-powered-by: Express
access-control-allow-origin: https://aasaanmerchant.aasaancheckout.com
vary: Origin
access-control-allow-credentials: true
access-control-expose-headers: Access-Control-Allow-Origin
x-frame-options: DENY
ratelimit-limit: 4
ratelimit-remaining: 3
ratelimit-reset: 894
etag: W/"55-0AGZZoNQmHjnZm+9v14hT58th1M"
X-Firefox-Spdy: h2




-------------------

POST /api/merchant/checkMerchantOTP HTTP/2
Host: aasaanapi.aasaancheckout.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Authorization: Bearer null
Content-Type: application/json
Content-Length: 36
Origin: https://aasaanmerchant.aasaancheckout.com
Connection: keep-alive
Referer: https://aasaanmerchant.aasaancheckout.com/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
TE: trailers


HTTP/2 200 OK
date: Sat, 10 Jun 2023 14:37:14 GMT
content-type: application/json; charset=utf-8
content-length: 85
x-powered-by: Express
access-control-allow-origin: https://aasaanmerchant.aasaancheckout.com
vary: Origin
access-control-allow-credentials: true
access-control-expose-headers: Access-Control-Allow-Origin
x-frame-options: DENY
ratelimit-limit: 4
ratelimit-remaining: 2
ratelimit-reset: 869
etag: W/"55-0AGZZoNQmHjnZm+9v14hT58th1M"
X-Firefox-Spdy: h2


-------------------------------------------------------------------

POST /api/merchant/checkMerchantOTP HTTP/2
Host: aasaanapi.aasaancheckout.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Authorization: Bearer null
Content-Type: application/json
Content-Length: 36
Origin: https://aasaanmerchant.aasaancheckout.com
Connection: keep-alive
Referer: https://aasaanmerchant.aasaancheckout.com/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
TE: trailers

HTTP/2 200 OK
date: Sat, 10 Jun 2023 14:37:37 GMT
content-type: application/json; charset=utf-8
content-length: 85
x-powered-by: Express
access-control-allow-origin: https://aasaanmerchant.aasaancheckout.com
vary: Origin
access-control-allow-credentials: true
access-control-expose-headers: Access-Control-Allow-Origin
x-frame-options: DENY
ratelimit-limit: 4
ratelimit-remaining: 3
ratelimit-reset: 846
etag: W/"55-0AGZZoNQmHjnZm+9v14hT58th1M"
X-Firefox-Spdy: h2


----------------------------

POST /api/merchant/checkMerchantOTP HTTP/2
Host: aasaanapi.aasaancheckout.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Authorization: Bearer null
Content-Type: application/json
Content-Length: 36
Origin: https://aasaanmerchant.aasaancheckout.com
Connection: keep-alive
Referer: https://aasaanmerchant.aasaancheckout.com/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
TE: trailers

HTTP/2 200 OK
date: Sat, 10 Jun 2023 14:37:58 GMT
content-type: application/json; charset=utf-8
content-length: 85
x-powered-by: Express
access-control-allow-origin: https://aasaanmerchant.aasaancheckout.com
vary: Origin
access-control-allow-credentials: true
access-control-expose-headers: Access-Control-Allow-Origin
x-frame-options: DENY
ratelimit-limit: 4
ratelimit-remaining: 1
ratelimit-reset: 825
etag: W/"55-0AGZZoNQmHjnZm+9v14hT58th1M"
X-Firefox-Spdy: h2

-----------------------------------

POST /api/merchant/checkMerchantOTP HTTP/2
Host: aasaanapi.aasaancheckout.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Authorization: Bearer null
Content-Type: application/json
Content-Length: 36
Origin: https://aasaanmerchant.aasaancheckout.com
Connection: keep-alive
Referer: https://aasaanmerchant.aasaancheckout.com/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
TE: trailers


HTTP/2 200 OK
date: Sat, 10 Jun 2023 14:38:23 GMT
content-type: application/json; charset=utf-8
content-length: 85
x-powered-by: Express
access-control-allow-origin: https://aasaanmerchant.aasaancheckout.com
vary: Origin
access-control-allow-credentials: true
access-control-expose-headers: Access-Control-Allow-Origin
x-frame-options: DENY
ratelimit-limit: 4
ratelimit-remaining: 2
ratelimit-reset: 800
etag: W/"55-0AGZZoNQmHjnZm+9v14hT58th1M"
X-Firefox-Spdy: h2

-----------------------------------------------------------------

POST /api/merchant/checkMerchantOTP HTTP/2
Host: aasaanapi.aasaancheckout.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Authorization: Bearer null
Content-Type: application/json
Content-Length: 36
Origin: https://aasaanmerchant.aasaancheckout.com
Connection: keep-alive
Referer: https://aasaanmerchant.aasaancheckout.com/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
TE: trailers


HTTP/2 200 OK
date: Sat, 10 Jun 2023 14:38:46 GMT
content-type: application/json; charset=utf-8
content-length: 85
x-powered-by: Express
access-control-allow-origin: https://aasaanmerchant.aasaancheckout.com
vary: Origin
access-control-allow-credentials: true
access-control-expose-headers: Access-Control-Allow-Origin
x-frame-options: DENY
ratelimit-limit: 4
ratelimit-remaining: 0
ratelimit-reset: 777
etag: W/"55-0AGZZoNQmHjnZm+9v14hT58th1M"
X-Firefox-Spdy: h2


----------------------------------------------

POST /api/merchant/checkMerchantOTP HTTP/2
Host: aasaanapi.aasaancheckout.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Authorization: Bearer null
Content-Type: application/json
Content-Length: 36
Origin: https://aasaanmerchant.aasaancheckout.com
Connection: keep-alive
Referer: https://aasaanmerchant.aasaancheckout.com/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
TE: trailers


HTTP/2 200 OK
date: Sat, 10 Jun 2023 14:39:14 GMT
content-type: application/json; charset=utf-8
content-length: 85
x-powered-by: Express
access-control-allow-origin: https://aasaanmerchant.aasaancheckout.com
vary: Origin
access-control-allow-credentials: true
access-control-expose-headers: Access-Control-Allow-Origin
x-frame-options: DENY
ratelimit-limit: 4
ratelimit-remaining: 1
ratelimit-reset: 749
etag: W/"55-0AGZZoNQmHjnZm+9v14hT58th1M"
X-Firefox-Spdy: h2

**Comment by gamemaker1** [comment]
Hi @Rajdev2011,

Thanks for sharing the headers. There's definitely a problem here, the hit count should not fluctuate like that.

Could you please modify [this test project](https://github.com/gamemaker1/test/tree/rate-limit-repro) till it looks exactly like your code, including the part where you register the rate limiter for the route? That should help us debug the problem further.

Thanks

**Comment by nfriedly** [comment]
hey @Rajdev2011 , are you running more than one node.js process, e.g. via the `cluster` module, or by running multiple servers behind a load balancer?

The default memory store only has local state, so if subsequent requests go to different instances, then it will get different results.

The way to avoid this is by using an external store (currently redis, memcached, or mongodb) to allow the instances to coordinate: https://github.com/express-rate-limit/express-rate-limit#store

**Comment by Rajdev2011** [comment]
Hi @gamemaker1  

Should i setup the test app in the server and give the logs to you

**Comment by gamemaker1** [comment]
@Rajdev2011 yes please, that would be very helpful.

As @nfriedly said, the problem might be `pm2` spinning up a new instance of the app every time the server is called.

**Comment by Rajdev2011** [comment]
Hi 

i used https://github.com/express-rate-limit/express-rate-limit#store with mongodb and its working fine but having one more issue in this ratelimit count is multiply 2 

example 

`Access-Control-Allow-Credentials:
true
Access-Control-Allow-Origin:
https://aasaanmerchant.aasaancheckout.com
Access-Control-Expose-Headers:
Access-Control-Allow-Origin
Content-Length:
51
Content-Type:
application/json; charset=utf-8
Date:
Tue, 27 Jun 2023 16:57:51 GMT
Etag:
W/"33-mTNFNCN/tkX6uq64X5e6BCmgQnc"
Vary:
Origin
X-Frame-Options:
DENY
X-Powered-By:
Express
X-Ratelimit-Limit:
6

X-Ratelimit-Remaining:
2
X-Ratelimit-Reset:
1687885970`


`Access-Control-Allow-Credentials:
true
Access-Control-Allow-Origin:
https://aasaanmerchant.aasaancheckout.com
Access-Control-Expose-Headers:
Access-Control-Allow-Origin
Content-Length:
51
Content-Type:
application/json; charset=utf-8
Date:
Tue, 27 Jun 2023 16:57:49 GMT
Etag:
W/"33-mTNFNCN/tkX6uq64X5e6BCmgQnc"
Vary:
Origin
X-Frame-Options:
DENY
X-Powered-By:
Express
X-Ratelimit-Limit:
6
X-Ratelimit-Remaining:
4
X-Ratelimit-Reset:
1687885970`


``

**Comment by nfriedly** [comment]
Is there any chance that `merchantOtpLimiter` is getting called more than once?  Perhaps via `app.use(merchantOtpLimiter)` and `app.get('*', merchantOtpLimiter, /*...*/);` or something similar to that?

Or, perhaps you're loading some asset, such as the favicon, that is also counting against the limit?

**Comment by Rajdev2011** [comment]
```
  app.use('/api/merchant/checkMerchantOTP', merchantOtpLimiter, function (req, res, next) {
        req.app.locals.merchantOtpLimiter = merchantOtpLimiter;
        next();
    });
```
    
    iam using above code in app.js does this cause

**Comment by nfriedly** [comment]
Running `app.use('/api/merchant/checkMerchantOTP', merchantOtpLimiter);` will cause the limiter to be applied to every request to `/api/merchant/checkMerchantOTP`. That should be all you need.

You should ***not*** be doing the `req.app.locals.merchantOtpLimiter = merchantOtpLimiter;` part. If you call `req.app.locals.merchantOtpLimiter(...)` later on, then that would cause each request to get double counted. 

(As an aside, `app.locals` only need to be set once, not on each request. `req.app.locals` should really be treated as read-only, with `req.locals` being used for per-request things. But, to be clear, `merchantOtpLimiter` should not be in *any* `.locals`.)
