### ISSUE TITLE
`package.json` exports and types are not compatible with TypeScript's `node16` `moduleResolution`

### ISSUE THREAD

**Issue by AlCalzone** [express-rate-limit/express-rate-limit#355]
### Description

TypeScript added a new module resolution strategy `node16` that better mimicks Node.js. Only under this option (or `nodenext`) is the `exports` field evaluated.

When authoring a `.ts` file in a CommonJS project and using this import
```ts
import rateLimit from 'express-rate-limit'
```
TypeScript complains about trying to require an ES module from CommonJS. This is because there's only one `.d.ts` file for both the CJS and ESM entrypoint and TypeScript considers that to be ESM due to the nearest `package.json`.
https://www.typescriptlang.org/docs/handbook/esm-node.html#packagejson-exports-imports-and-self-referencing mentions at the bottom that each needs their own declaration file.

As awkward as this is, this can be fixed by
1. renaming `index.d.ts` to `index.d.mts`
2. copying `index.d.mts` to `index.d.cts`
3. changing the `package.json` exports like this:
```
	"exports": {
		".": {
			"import": {
				"types": "./dist/index.d.mts",
				"default": "./dist/index.mjs"
			},
			"require": {
				"types": "./dist/index.d.cts",
				"default": "./dist/index.cjs"
			}
		}
	},
```

### Library version

6.7.0

### Node version

16.20.0

### Typescript version (if you are using it)

5.1.6

### Module system

CommonJS

**Comment by gamemaker1** [comment]
Hi @AlCalzone,

Thanks for detailing the issue and the solution so nicely :)

I'll make a PR for this once I get to a computer, unless you want to take a crack at it?

Regards,
Vedant
