### ISSUE TITLE
limit is not working , still need to set max 

### ISSUE THREAD

**Issue by geminigeek** [express-rate-limit/express-rate-limit#384]
### Description

the example do not work while using limit

```
const apiLimiter = rateLimit({
	windowMs: 15 * 60 * 1000, // 15 minutes
	limit: 100, // Limit each IP to 100 requests per `window` (here, per 15 minutes)
	standardHeaders: 'draft-7', // Set `RateLimit` and `RateLimit-Policy`` headers
	legacyHeaders: false, // Disable the `X-RateLimit-*` headers
	// store: ... , // Use an external store for more precise rate limiting
})
````

### Library version

 "express-rate-limit": "^6.10.0",

### Node version

v18.15.0

### Module system

ESM

**Comment by geminigeek** [comment]
the limit will come in effect from v7,  its working , the documents are confusing

**Comment by nfriedly** [comment]
Yeah, sorry for the confusion here. We're in the process of making some changes. 

If you install from npm, the documentation there should be correct: https://www.npmjs.com/package/express-rate-limit

Alternatively, to use the documentation on github, you would want to install from GitHub. (I believe it will automatically compile typescript to JavaScript that install time when you install from GitHub, although I haven't tried it recently.)

In general, I'd recommend sticking with npm, though. We're not quite ready for our v7 release.

**Comment by nfriedly** [comment]
@gamemaker1 I suppose we could put out a 6.11 release that backports support for `limit`. But I think we'll have the seven out pretty soon, so it should be a moot point then.

**Comment by gamemaker1** [comment]
Yea, we should have v7 out pretty soon.

To avoid something like this happening in the future, should we have a `next` branch where we work on the next release, and the `main` branch has the code for the latest release?

**Comment by nfriedly** [comment]
> should we have a next branch where we work on the next release, and the main branch has the code for the latest release?

Yeah, at least if we're doing a big set of changes like we are right now.
