### ISSUE TITLE
ERR_ERL_DOUBLE_COUNT with multiple rate limits

### ISSUE THREAD

**Issue by nfriedly** [express-rate-limit/express-rate-limit#395]
### Discussed in https://github.com/express-rate-limit/express-rate-limit/discussions/393

<div type='discussions-op-text'>

<sup>Originally posted by **stephent** September  9, 2023</sup>
Before this warning was added, I'd had multiple rate limits configured for a long time, all pointing to the same Redis store. With the addition of the warning, the double counting is now apparent.

However, wouldn't it be a friendlier approach to have the library look after unique scoping keys per configured rate limit rather than imposing this on the library user? If you're able to configure multiple rate limits, I suspect many would naturally assume this would already be the case by default, but it seems not.

(Not sure if there are other use cases which make this difficult or undesirable to implement?)

UDPATE: on reviewing my code more thoroughly, I see I already have unique `prefix` values per rate limit for the RedisStore. Confused as to why I'm seeing this error...</div>

**Comment by stephent** [comment]
@nfriedly thanks for the super quick response! I'll give the patch version a go tomorrow.

**Comment by nfriedly** [comment]
@stephent no problem. We went ahead and released it, so you can ignore my instructions for testing the git source, and just try out version 6.11.1 from npm instead.
