### ISSUE TITLE
It blocks all IPs instead of blocking each IP

### ISSUE THREAD

**Issue by m0x61h0x64i** [express-rate-limit/express-rate-limit#401]
### Description

Hello, I used this package like this : 
```
const { rateLimit } = require('express-rate-limit')

const limiter = rateLimit({
	windowMs: 30 * 1000, // 30 sec
	limit: 1, // Limit each IP to 1 requests per `window`
	standardHeaders: 'draft-7', // draft-6: `RateLimit-*` headers; draft-7: combined `RateLimit` header
	legacyHeaders: false
})

// Apply the rate limiting middleware to all requests
app.use(limiter)
app.get('/', handleRequest)
```

Now the problem is that, when i used two broswers two access my endpoint at '/', At the first request It shows the result and at the second request it shows "Too many requests, please try again later." thats fine but when i open the endpoin (127.0.0.1:3000/) in another browser, it shows "Too many requests, please try again later.", as documented it should limit each IP to 1 request, but it blocks all IP requests when it hits the limits.

I also tried hosting my express webserver on ngrok and i got the same result (No requests can be done successfully at the limit duration when only one IP reaches the rate limit count) 

The problem is that when one IP reaches the limit count, All other IPs cant send even one request (not only localhost IPs but also remote host IPs are the same)

There was a issue about this earlier, their said about proxy but i dont know about proxy and i didnt set any proxy

### Library version

7.0.1

### Node version

18.17.0

### Module system

CommonJS

**Comment by nfriedly** [comment]
Are these two browsers using the same computer, or two computers on the same network? If so, they're likely sharing the same IP.

If you have smartphone you can turn off WiFi to force it to use cellular data, and then use it to access the site; that's an easy way to test from a second IP.

**Comment by nfriedly** [comment]
Oh, I believe ngrok is a proxy, so you would need to take the proxy settings in their account to use it.

**Comment by m0x61h0x64i** [comment]
@nfriedly Thanks for your reply, few moments ago I deployed this simple app on vercel, there it gave me a domain and i used that domain to connect to the express webserver from two different devices with different IPs, again i got the same result (No requests can be done successfully at the limit duration when only one IP reaches the rate limit count)

I tested it using two scenarios:
1. using VPN
domain: vercel
device 1: laptop with vpn on
device 2: smartphone wih vpn on
note: each using different IP as VPN

3. without vpn
domain: vercel
device 1: laptop with vpn off
device 2: smartphone wih vpn off
note: each using different IP

I found the IPs and say results from this code so you can trust it that i was getting different IPs for the test:
```
res.status(200).json({ message: `Request processed successfully. ${req.headers['x-forwarded-for'] || req.connection.remoteAddress}` })
```

**Comment by nfriedly** [comment]
Vercel is almost certainly using a reverse proxy also, that's what would be setting `req.headers['x-forwarded-for']`

`req.ip` is the IP that express-rate-limit uses.


Try doing `app.set('trust proxy', 1)`; that will tell express that it can trust the x-forwarded-header

**Comment by m0x61h0x64i** [comment]
Thanks @nfriedly, When i changed the way of showing the IPs like this : 
```
res.status(200).json({ message: `Request processed successfully. ${req.headers['x-forwarded-for'] || req.connection.remoteAddress}` })
```
i got this: 
```
127.0.0.1
```

My question here is that why do i have to use `app.set('trust proxy', 1)` when i can fix it by adding `keyGenerator: (req, res) => req.headers['x-forwarded-for'] || req.connection.remoteAddress` option, which way is better ?

**Comment by nfriedly** [comment]
> My question here is that why do i have to use app.set('trust proxy', 1) when i can fix it by adding keyGenerator: (req, res) => req.headers['x-forwarded-for'] || req.connection.remoteAddress option, which way is better ?

Anyone can set an `X-Forwarded-For` header, and while a proxy may be configured to strip them out, the more common behavior is to just append. 

In node.js, `req.headers['x-forwarded-for']` is a comma separated list of all the header values if there are more than one. So malicious user could set the header to a random value for each request and get effectively unlimited requests doing it your way.

Setting `'trust proxy', 1`, on the other hand, looks at only the nearest proxy (the last value). So it will ignore any random crap that a malicious user may set in their own x-forwarded-for header.

**Comment by m0x61h0x64i** [comment]
@nfriedly Thanks, that helped a lot

**Comment by m0x61h0x64i** [comment]
Hello @nfriedly, I was looking for a way to implement a rate limit per IP but its vulnerable to making requests using proxy list to the rate limit middleware, now im looking for a way to Implement both IP limit and total requests limit, previously I could limit all requests to an endpoint but after implementing IP limit I cant implement limit for all requests, How is this possible to implement both limits ? (limit per IP and limit per total requests)
