### ISSUE TITLE
Install a problem in express5 / express@next

### ISSUE THREAD

**Issue by 332lfgb6** [express-rate-limit/express-rate-limit#415]
### Description

![image](https://github.com/express-rate-limit/express-rate-limit/assets/51245335/67cbd511-a199-4b67-8dd1-9881a8ae5b36)

### Library version

latest

### Node version

18.16.0

### Module system

CommonJS

**Comment by nfriedly** [comment]
Hum, I wonder if the `^` prevents it from accepting beta versions?

**Comment by 332lfgb6** [comment]
> Ok, can you try installing the `peer-dep` branch from #416 and let me know if that works for you?
> 
> `npm install "https://github.com/express-rate-limit/express-rate-limit.git#peer-dep"`

npm install "https://github.com/express-rate-limit/express-rate-limit.git#peer-dep" fail
![image](https://github.com/express-rate-limit/express-rate-limit/assets/51245335/3800135b-24d6-4684-8807-f31e6ce8e5e1)
but npm install express-rate-limit@2 works well.

**Comment by 332lfgb6** [comment]
Maybe there's something wrong with my Internet

**Comment by nfriedly** [comment]
> npm install "https://github.com/express-rate-limit/express-rate-limit.git#peer-dep" fail
> ...

Hum, I don't think I'm seeing the actual error there. Could you copy and paste the full text rather than taking a screenshot?

**Comment by 332lfgb6** [comment]
> > npm install "https://github.com/express-rate-limit/express-rate-limit.git#peer-dep" fail
> > ...
> 
> Hum, I don't think I'm seeing the actual error there. Could you copy and paste the full text rather than taking a screenshot?

### fail
![image](https://github.com/express-rate-limit/express-rate-limit/assets/51245335/c4405f06-5085-4f88-b0fc-2a6e5f3bb4c6)
![image](https://github.com/express-rate-limit/express-rate-limit/assets/51245335/e6c87e8e-d3fd-4a1a-9b8e-c3cca5314536)
![image](https://github.com/express-rate-limit/express-rate-limit/assets/51245335/5fc9bb9e-dab6-4e23-af56-fcc525f22d9a)
### v2 normally
![image](https://github.com/express-rate-limit/express-rate-limit/assets/51245335/cc74a291-55e1-46e1-86dd-960d61fdda64)

**Comment by nfriedly** [comment]
Huh, that's a different error. Building the types is failing for some reason. But that wouldn't normally be necessary, they're pre-built when you install from npm instead of github.

I think I'm going to merge in #416 and publish it.

**Comment by 332lfgb6** [comment]
> npm install express-rate-limit@7.1.3

good
![image](https://github.com/express-rate-limit/express-rate-limit/assets/51245335/c3a9da47-78c1-44fb-8a93-964256105175)
