### ISSUE TITLE
Can't get the correct ip 

### ISSUE THREAD

**Issue by abdimussa87** [express-rate-limit/express-rate-limit#417]
### Description

I'm using cloudflare as a dns provider and each time a request is sent, the req.ip holds the ip address of cloudflare's and not the client's. I've tried using the below code:

`app.set("trust proxy", 1);` 

Then sending a request to this endpoint:

`app.get("/ip", (request, response) =>  response.send(request.ip);
`

Returns cloudflare's ip. I tried increasing the `trust proxy` up to 21, but still not getting the actual client's ip. How can I resolve this issue?

### Library version

7.1.3

### Node version

18.15.0

### Module system

ESM

**Comment by nfriedly** [comment]
Can you make an endpoint like this:

```
app.get('/test', (req, res) => res.send(req.headers));
```

And show me what that reports, along with what your correct IP is?

Also, do you know if your ISP uses [CGNAT](https://en.wikipedia.org/wiki/Carrier-grade_NAT)?

**Comment by nfriedly** [comment]
Oh, and please verify that you __do not__ have the ["Remove visitor IP headers" Managed Transform enabled](https://developers.cloudflare.com/fundamentals/reference/http-request-headers/#cf-connecting-ip).

**Comment by nfriedly** [comment]
Since we haven't heard anything back, I'm going to go ahead and close this. Feel free to re-open or file a new issue if appropriate.
