### ISSUE TITLE
Ratelimit headers empty while running on Bun v1.0.x

### ISSUE THREAD

**Issue by MikkelSVDK** [express-rate-limit/express-rate-limit#418]
### Description

I've been creating a little project with bun as the runtime env, but I've noticed that the headers are always empty, even though the info variable has the information as seen in the photo below.
![image](https://github.com/express-rate-limit/express-rate-limit/assets/31735044/f8031fa5-67dc-46c0-adb9-2e5e971bf8c8)

I simply added .toString() and it return the correct information in the headers
![image](https://github.com/express-rate-limit/express-rate-limit/assets/31735044/515b93c9-4c9a-4df5-8822-46ce31eb87b0)

### Library version

7.1.3

### Node version

bun 1.0.7

### Typescript version (if you are using it)

6.0.0

### Module system

ESM

**Comment by nfriedly** [comment]
Fixed by #419
