### ISSUE TITLE
Don't know how to resetKey when user complete captcha

### ISSUE THREAD

**Issue by phvietan** [express-rate-limit/express-rate-limit#424]
### Description

I read on the old documentation, it seems express-rate-limit in the past supported the feature for the server to `resetKey` when user complete captcha ( https://bestofjs.org/projects/express-rate-limit ).

However, in the current version I couldn't find a way to do it.

### Library version

7.1.4

### Node version

*

### Module system

ESM

**Comment by nfriedly** [comment]
Oh, shoot, we might have lost that in the transition. I'll add it back soon.

In the meanwhile, here is the old docs, and the method itself should continue to work: https://github.com/express-rate-limit/express-rate-limit/blob/v7.1.0/readme.md#instance-api

**Comment by nfriedly** [comment]
Ok, this is now documented at https://express-rate-limit.mintlify.app/reference/instance-api#resetkey-key

**Comment by phvietan** [comment]
Hi @nfriedly  , can I ask how to get the instance of the store in my route ? For example:

```
app.post('/login', (req, res) => {
  if (checkCaptcha(req.captcha)) {
    // How to get rate limit store to reset ?
    res.rateLimitStore.resetKey(req.ip); 
  }
  ...
});
```

**Comment by nfriedly** [comment]
You'd have to get it earlier on:

```ts
import { rateLimit } from 'express-rate-limit'

const limiter = rateLimit({
	// ...
})

// Make sure the limiter doesn't apply to the reset URL!
app.post('/login', async (req, res) => {
   if (checkCaptcha(req.captcha)) {
     limiter.resetKey(req.ip);res.rateLimitStore.resetKey(req.ip); 
   }
  // ...
})

app.use(limiter)
```

---

Also, I noticed that you used `'/login'` in your example - if your users are logged in, then you could create a custom `keyGenerator` that returns the user ID for logged in users, or the IP for anonymous users. 

That would provide a few benefits:
* It would effectively reset the limit when the user logs in
* Multiple users on the same IP (e.g. in a school classroom) would get their own limits
* You could provide higher limits to logged in users than to anonymous ones

**Comment by phvietan** [comment]
Yay thank you for your detail explanation

**Comment by nfriedly** [comment]
You're welcome, thank you for the sponsorship!
