### ISSUE TITLE
An option similar to `skip` but which is evaluated after the request has completed

### ISSUE THREAD

**Issue by oneEyedSunday** [express-rate-limit/express-rate-limit#429]
### Description

Hello there, I have a use Case where i'd like to only skip on 422 errors (so `skipFailedRequests` doesnt quite cover my use case. I tried to create something with `skip`, see below:

```javascript
const rateLimitByTimeInSecFn = (timeSec, bucketSize, keySuffix = undefined) => rateLimit({
  windowMs: timeSec * 1000,
  max: bucketSize,
  // errors may reprsent pressure on API, except perhaps a 422
  skipFailedRequests: false,
  // We want to only skip 422s
  // This seems to only query against the request, not the response
  skip: (req, res) => {
    return [StatusCodes.UNPROCESSABLE_ENTITY].includes(res.statusCode);
  },
  // Default to IP address
  // Or force the same key
  // if provided, use, else default
  keyGenerator: keySuffix ? () => keySuffix : undefined,
  store: new RedisStore({
    passIfNotConnected: true, // If Redis is not connected, let the request succeed as failover
    // see https://github.com/wyattjoh/rate-limit-redis#examples
    sendCommand: (...args) => redisClient.call(...args),
    prefix: `rate-limit-time:${timeSec}sec:`,
  }),
});

```

### Why

For use cases where we want to only skip on certain error types, usually a 422 or any 4xx errors, so faulty user requests dont count against their quota

### Alternatives

Existing alternatives are `skipFailedRequests` but i want to be able to evaluate whether to skip after the response has been acquired.

Although in my case, I could perhaps run the validator inside the `skip` option.

**Comment by nfriedly** [comment]
Hi @oneEyedSunday 

I think a combination of `skipFailedRequests` and a custom [`requestWasSuccessful`](https://express-rate-limit.mintlify.app/reference/configuration#requestwassuccessful) would work for you:

```js
const rateLimitByTimeInSecFn = (timeSec, bucketSize, keySuffix = undefined) => rateLimit({
  windowMs: timeSec * 1000,
  max: bucketSize,
  // all requests initially counts against the quota, but then 422 ones are un-counted
  skipFailedRequests: true,
  // We want to only skip 422s - everything else counts against the quota
  requestWasSuccessful: (req, res) => {
    return ![StatusCodes.UNPROCESSABLE_ENTITY].includes(res.statusCode);
  },
  // Default to IP address
  // Or force the same key
  // if provided, use, else default
  keyGenerator: keySuffix ? () => keySuffix : undefined,
  store: new RedisStore({
    passIfNotConnected: true, // If Redis is not connected, let the request succeed as failover
    // see https://github.com/wyattjoh/rate-limit-redis#examples
    sendCommand: (...args) => redisClient.call(...args),
    prefix: `rate-limit-time:${timeSec}sec:`,
  }),
});
```

The limiter basically has to run before the request if there is any chance that it needs to block it. The skipSuccessfulRequests and skipFailedRequests options both initially count the request against the quota and block it if the user is over their quota, but after the request is completed they then un-count if the conditions are meant.

**Comment by oneEyedSunday** [comment]
Hello, thanks for the reply @nfriedly 
This should work very well.
