### ISSUE TITLE
Allow other middleware res send methods in message handler function

### ISSUE THREAD

**Issue by jfoclpf** [express-rate-limit/express-rate-limit#460]
### Description

Regarding the message handler, the [docs](https://express-rate-limit.mintlify.app/reference/configuration#message) mention:

```js
const limiter = rateLimit({
	// ...
	message: async (req, res) => {
		if (await isPremium(req.user))
			return 'You can only make 10 requests every hour.'
		else return 'You can only make 5 requests every hour.'
	},
})
```

Though, I want to be able to use `res` own methods, but the handler expects the return of the text to be sent.

What I need, for example:

```js
import express from 'express';
import { engine } from 'express-handlebars';
import { rateLimit } from 'express-rate-limit'

const app = express();

app.engine('handlebars', engine());
app.set('view engine', 'handlebars');
app.set('views', './views');

/*....*/

const limiter = rateLimit({
	// ...
	message: (req, res) => {
		if (isJson(req))
			res.json({msg: 'JSON response'})
		else 
                        res.render('Message_Limit') // Message_Limit is a handlebars template
	}
})

app.use(limiter)
app.listen(3000)
```

### Why

It would allow us to to use in the message handler other middleware methods to send the final message

### Alternatives

Right now I don't find any alternative

**Comment by nfriedly** [comment]
I think you could accomplish your goal by defining a custom [handler](https://express-rate-limit.mintlify.app/reference/configuration#handler) rather than by setting `message`.

`message` handles most common cases, but `handler` is there for the more advanced cases like you want. Perhaps I should add a note to the docs to clarify this.

**Comment by jfoclpf** [comment]
Uau, that's exactly that, the broad term "handler" seemed vague but I guess is what I need.

**Comment by jfoclpf** [comment]
thanks a lot, it's working!
