### ISSUE TITLE
legacyHeaders is off but x-header return in response 

### ISSUE THREAD

**Issue by mohamadbadrian** [express-rate-limit/express-rate-limit#463]
### Description

i use this middleware in my express app . 

```js
const rateLimit = require('express-rate-limit');

const authLimiter = rateLimit({
  windowMs: 5 * 60 * 1000,
  max: 3,
  skipSuccessfulRequests: false,
  legacyHeaders: false,
});

module.exports = {
  authLimiter,
};

// in app.js
if (config.env === 'production') {
  app.use('/v1/auth', authLimiter);
}
```

the limiter is work well but response still return X-RateLimit header , any suggestion?

### Library version

5.0.0

### Node version

18.14.0

### Module system

CommonJS

**Comment by gamemaker1** [comment]
Hi @mohamadbadrian,

Since you're using version 5.0.0 of the library, you have to use the `headers` option instead of the `standardHeaders` and `legacyHeaders` options.

To disable the headers, set `headers: false`, like so:

```diff
const rateLimit = require('express-rate-limit');

const authLimiter = rateLimit({
  windowMs: 5 * 60 * 1000,
  max: 3,
  skipSuccessfulRequests: false,
-  legacyHeaders: false,
+  headers: false,
});

module.exports = {
  authLimiter,
};

// in app.js
if (config.env === 'production') {
  app.use('/v1/auth', authLimiter);
}
```

**Comment by gamemaker1** [comment]
You can view the configuration options for v5.0.0 [here](https://github.com/express-rate-limit/express-rate-limit/tree/v5.0.0?tab=readme-ov-file#configuration-options).
