### ISSUE TITLE
Rate limit always called 1 more time than configured

### ISSUE THREAD

**Issue by yedi97** [express-rate-limit/express-rate-limit#468]
### Description

I'm having the problem that rate limit is always called more than once. For example, if I set limit to 1, it will be called 2 times, then it will work the third time. If I set limit to 2, it will be called 3 times. It wasn't until the 4th time that it worked, this gradually increased...

However, it works fine in the local environment, this error occurs when I deploy to the production environment, and the server I use nginx

I'm test with postman

This is my config:
```
// app.js file
const app = express();
app.set('trust proxy', 2 /* number of proxies between user and server */)

// router config file
const router = require("express").Router();
const rateLimit = require('express-rate-limit');
const limiter = rateLimit({
  windowMs: 0.5 * 60 * 1000, // 30 seconds
  limit: 1, // Limit each IP to 1 requests per `window` (here, per 30 seconds).
  standardHeaders: "draft-7", // Return rate limit info in the `RateLimit-*` headers
  legacyHeaders: false, // Disable the `X-RateLimit-*` headers
  message: {
    success: false,
    message: "Too many requests, please try again!",
  },
  keyGenerator: (req, res) => {
    if (!req.ip) {
      console.error('Warning: request.ip is missing!')
      return req.socket.remoteAddress
    }
    return req.ip.replace(/:\d+[^:]*$/, '')
  }
})
router.post("/test-rate-limit-87762", limiter, async (req, res) => {
  console.log('Test rate limit processing')
  return res.status(200).json({message: "Test rate limit processing"});
});
```

Nginx config file:
```
server{
    server_name api_url;
    location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
        proxy_pass http://127.0.0.1:8888;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 3000;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/api-url/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/api-url/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server{
    if ($host = api_url) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name api_url;
    return 404; # managed by Certbot
}
```

### Library version

7.3.1

### Node version

v16.17.1

### Module system

ESM

**Comment by nfriedly** [comment]
> I'm having the problem that rate limit is always called more than once.

Can you clarify what you mean by "called" here?

>  For example, if I set limit to 1, it will be called 2 times, then it will work the third time.

Are you saying that the first two requests get `{message: "Test rate limit processing"}`, then the third is blocked with `{ success: false, message: "Too many requests, please try again!" }` ?

**Comment by yedi97** [comment]
> > I'm having the problem that rate limit is always called more than once.
> 
> Can you clarify what you mean by "called" here?
> 
> > For example, if I set limit to 1, it will be called 2 times, then it will work the third time.
> 
> Are you saying that the first two requests get `{message: "Test rate limit processing"}`, then the third is blocked with `{ success: false, message: "Too many requests, please try again!" }` ?

Yes, exactly

**Comment by yedi97** [comment]
It worked, I didn't have problems with the proxy, the source was because on the server I was running with multiple nodes, thank @nfriedly
