### ISSUE TITLE
Severe: Incorrect limit count (!) at rateLimit

### ISSUE THREAD

**Issue by GreenFlag31** [express-rate-limit/express-rate-limit#469]
### Description

Hi. 
I just define my rateLimit as following:

``` javascript 
   const limiter = rateLimit({
      windowMs: 15 * 60 * 1000, // 15 minutes
      limit: 1,
      message: [
        {
          code: SuperErrorCodeAPi.TOO_MANY_REQUESTS,
          type: "Rate limit",
          message: "Please try again later",
        },
      ],
    });
```

The rateLimit is added on a particular route, not globally. The rateLimiter will be correctly executed in first place:
![image](https://github.com/express-rate-limit/express-rate-limit/assets/84795623/a7218eee-1b3e-4197-99dd-5d4e565f70d9)

If I log (log((req as any).rateLimit)), I got the limit reset back to default: 
![image](https://github.com/express-rate-limit/express-rate-limit/assets/84795623/64e559d9-c2f2-41e7-82fc-1c017c6378e7)
All other options are correctly set (windowMS, the message, etc).

If now I add the (legacy) 'max' option (which has been renamed to 'limit' according to the documentation): it now correctly works:
``` javascript 
   const limiter = rateLimit({
      windowMs: 15 * 60 * 1000, // 15 minutes
      limit: 1,
      max: 1,
      message: [
        {
          code: SuperErrorCodeAPi.TOO_MANY_REQUESTS,
          type: "Rate limit",
          message: "Please try again later",
        },
      ],
    });
```
![image](https://github.com/express-rate-limit/express-rate-limit/assets/84795623/f869e8cc-cdac-440d-bcf2-5938e854609c)

### Library version

 "express-rate-limit": "^7.3.1",

### Node version

v20.14.0

### Typescript version (if you are using it)

"typescript": "^4.6.2"

### Module system

CommonJS

**Comment by nfriedly** [comment]
Could you run the command `npm ls express-rate-limit` and let me know what it reports?

**Comment by GreenFlag31** [comment]
Sure,
npm ls express-rate-limit : 
![image](https://github.com/express-rate-limit/express-rate-limit/assets/84795623/7f73a10a-b399-48a5-bc5c-496cf149c26c)

**Comment by nfriedly** [comment]
Ok, thanks, that rules out one thing. I'm looking to see if I can figure out what's going on.

**Comment by nfriedly** [comment]
I just added one test and tweaked another to try and recreate the issue, but both are passing.

I'd like to know more about this screenshot - what is it configuring?
> ![image](https://github.com/express-rate-limit/express-rate-limit/assets/84795623/a7218eee-1b3e-4197-99dd-5d4e565f70d9)

**Comment by GreenFlag31** [comment]
The bug is hard to reproduce, but I can tell you more about the context.

I'm building a library that uses express-rate-limit. The library takes the option provided by the user: 
```javascript
const limit: Partial<Options> = {
  windowMs: 15 * 60 * 1000, // 15 minutes
  limit: 1,
};
```
and then add it as a middleware to a specific route:
```javascript

  /**
   * Add rate limiter on a specific route if option is present.
   */
  private addRateLimit(routeData: SuperRoute) {
    const limitOptions = routeData.rateLimit;
    if (!limitOptions) return [];


    const response = {
      code: SuperErrorCodeAPi.TOO_MANY_REQUESTS,
      message: "Too many",
      name: "rateLimitError",
    };

    const limiter = rateLimit({
      ...limitOptions.option,
      // max: limitOptions.option.limit,
      handler: (req, res, next, options) => {
        next(response);
      },
    });

    return limiter;
  }
```

thus the context of execution of the rate limiter is not as I mistakenly have provided, but rather the following one, since it occurs in the "consuming" application (the application that uses the library) : 
![image](https://github.com/express-rate-limit/express-rate-limit/assets/84795623/7bf8487d-a4bd-4092-aed3-f335cc430ade)


I don't know if this can help you, but I will create a repo on Github when I will have time (not today), so you can clone it and identify the problem.

Thank you for your time.

**Comment by nfriedly** [comment]
Yeah, a repro app would be useful. 

That `@types/express-rate-limit@6.0.0` is a bit suspicious both because 6.0.0 was the release when the library was rewritten in typescript, and therefore didn't need external types anymore, and because in v6.0.0 `max` had not yet been renamed to `limit`. But, all the same, it looks like v7.3.1 is the installed version, so I'm not sure if the v6 types is relevant at all.

I'll take a look at the repo whenever you get it ready.

**Comment by nfriedly** [comment]
Hey, did you figure out what was going on here?

**Comment by GreenFlag31** [comment]
Unfortunately not, I was unable to reproduce the issue. I tried almost everything: npm rebuild, npm uninstall the lib and re installing etc.

What I know and what I think is happening: express rate limit was installed in this project long time ago (legacy project), and thus the 'max' option was the only available.  What I suppose to be happening is that _somehow_, even if indicating a modern version, it is still pointing to the old reference, hence the working limit when the legacy "max" option is added.
