### ISSUE TITLE
Skip does not work as expected

### ISSUE THREAD

**Issue by khalilp5** [express-rate-limit/express-rate-limit#470]
### Description

I have a few routes that I want to exclude from being rate-limited. I use the skip function to read the request path and then exclude the route. However, I noticed very strange behavior where every even request was not skipped, and the (n*2+1)th request (n being the limit) was still blocked. Please find the code snippet I am using for my rate limit middleware below.

```ts

import rateLimit from "express-rate-limit";

// Exclude webhook routes
const EXCLUDE_RATE_LIMIT_REGEX = /webhook/gi;

// Standard rate limit: 100 requests per minute
const standardRateLimiter = rateLimit({
  windowMs: 1 * 60 * 1000, // 1 minute
  limit: 10,
  message: {
    message: "Too many requests, please try again later",
  },
  standardHeaders: true,
  handler: (req, res, _, opitons) => {
    if (req.rateLimit.used === req.rateLimit.limit + 1) {
      console.log("Rate Limit Reached for " + req.path + " by " + req.ip);
    }
    return res.status(opitons.statusCode).json(opitons.message);
  },
  skip: (req) => {
    const shouldSkip = EXCLUDE_RATE_LIMIT_REGEX.test(req.path);
    console.log(`ShouldSkip: path: ${req.path}, skip: ${shouldSkip}`);
    return shouldSkip;
  },
  keyGenerator: (request) => {
    if (!request.ip) {
      console.error("Warning: request.ip is missing!");
      return request.socket.remoteAddress as string;
    }

    return request.ip.replace(/:\d+[^:]*$/, "");
  },
});

export default standardRateLimiter;


```

Output:
![image](https://github.com/user-attachments/assets/1c9e6f4d-9092-4b8b-8483-c18e68acc447)

### Library version

7.3.1

### Node version

20.14.0

### Typescript version (if you are using it)

5.3.3

### Module system

ESM

**Comment by nfriedly** [comment]
This is happening because you're re-using the same regex and it's remembering it's `lastIndex` - here's an example: https://jsbin.com/durevayiwu/edit?js,console

Omit the `g` flag to disable this behavior.

See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test#using_test_on_a_regex_with_the_global_flag for a bit more info.
