### ISSUE TITLE
Add support for emitting headers in IETF RateLimit Headers draft 8 format

### ISSUE THREAD

**Issue by nfriedly** [express-rate-limit/express-rate-limit#484]
### Description

https://datatracker.ietf.org/doc/html/draft-ietf-httpapi-ratelimit-headers-08 was just published about a week ago with some changes that we should add support for

### Why

--

### Alternatives

--

**Comment by nfriedly** [comment]
It sounds like we'll need an identifier, but that we can have separate header values for separate instances of the limiter that don't clobber each other!

For the identifier, we could default to a generic name like `default`, `rl`, or `erl`, possibly with a counter to handle multiple instances at once, so `rl`, `rl2`, etc. Or we could try to be a little smarter and make the name based on the config, e.g. if `limit` is 7 and `windowMs` is 60000, then name it `rl-7-60000` or `rl-7-min` or something like that. Or maybe just include the limit by default, e.g. "rl-7", since I don't imagine many situations where you'd have the same limit with different windows. I don't know...

I also haven't quite wrapped my head around the [Partition Key](https://datatracker.ietf.org/doc/html/draft-ietf-httpapi-ratelimit-headers-08#name-partition-key-parameter) param either - maybe it should be a hash of the `keyGenerator` result? But it's optional so I think we can omit it for now.

**Comment by gamemaker1** [comment]
Sorry for the delay, been swamped with exams. Working on a PR following the draft, and your message - will try finishing it today.

I just realised that the current `setDraftXHeader` implementations overwrite the previous value of the header instead of appending to it - so if there are multiple limiters, the last one to trigger is the one that gets the final say. However, in the drafts, it is mentioned that the lowest remaining quota is what should be put in the `RateLimit` header. Perhaps this deserves a separate PR and a backport?

**Comment by nfriedly** [comment]
No worries. I thought I'd have some time to work on this, but I haven't yet.

Good catch on `setDraftXHeader` - yeah, that should probably be a separate PR. Not sure if wee need to backport it, though, it feels like a fairly uncommon issue, and we try to make upgrading to the latest version as painless as possible. In the past, I've always recommended that folks with multiple limiters disable headers for all or all but one.

**Comment by gamemaker1** [comment]
Fixed the overwriting issue for draft 8 in the PR, but for draft 7 we will need a separate PR - the spec demands that the `RateLimit` header only contain the `limit`, `remaining` and `reset` for the quota closest to finishing.
