### ISSUE TITLE
Boundary Issue - Option to receive 429 when at limit, instead of limit + 1

### ISSUE THREAD

**Issue by chris-rickman** [express-rate-limit/express-rate-limit#487]
### Description

It makes sense for the default behavior to allow the number of requests expressed by the `limit` option and then fail after the `limit` has been met; however, there are certain cases where a 429 response is needed when the `limit` is met and not the `limit` + 1 case.

### Why

For example: When limiting on sign-in failure (`skipSuccessfulRequests`)...say 5 failures...429 is not returned until the 6th sign-in, and that sign-in may actually not be a failure.  The block is already in place, but it hasn't been messaged to the app or the user.

### Alternatives

If there is already a pattern to accomplish this, could you please share; otherwise, this may be nice refinement to allow a rate-limiter to opt-into blocking _at_ the `limit`.  I suppose on the regular case where you aren't counting failures, this could be accomplished by simply setting the limit to one less.  So perhaps, this is specific to when `skipSuccessfulRequests` is set to `true`.

**Comment by gamemaker1** [comment]
> The block is already in place, but it hasn't been messaged to the app or the user.

You could enable the rate limit headers (set `standardHeaders: true`, and `legacyHeaders: false`), use a library like [`ratelimit-header-parser`](https://github.com/express-rate-limit/ratelimit-header-parser) to parse them, and check how many requests are left. If there are 0 left, wait until the reset time to send the next one.

**Comment by chris-rickman** [comment]
I am using that header configuration, but new to express-rate-limit and didn't know about the client-side pattern.  Still think it'd be nice to just 429 on the failure that triggers the block, but this does seem like a viable suggestion (that doesn't require sharing server/api config with the client).

**Comment by chris-rickman** [comment]
That's a good point, I get that.  Thanks for the input.
